failure-step

diff --git a/.github/workflows/pr-code-check-only.yml b/.github/workflows/pr-code-check-only.yml
--- a/.github/workflows/pr-code-check-only.yml
+++ b/.github/workflows/pr-code-check-only.yml
@@ -47,15 +47,15 @@ jobs:
       - name: "Validate Deployment to DiegOrg"
         id: validate-deployment
         shell: bash
-        run: |
-          cat ./package/package.xml
-          if grep -q '<types>' package/package.xml;
-          then
-            sfdx project deploy validate --target-org ${{ secrets.SALESFORCE_DEVHUB_USERNAME }} --manifest package/package.xml --test-level RunLocalTests --verbose --wait 180 --json >> "$GITHUB.OUTPUT"
-          fi
+        run: exit 1
+#          cat ./package/package.xml
+#          if grep -q '<types>' package/package.xml;
+#          then
+#            sfdx project deploy validate --target-org ${{ secrets.SALESFORCE_DEVHUB_USERNAME }} --manifest package/package.xml --test-level RunLocalTests --verbose --wait 180 --json >> "$GITHUB.OUTPUT"
+ #         fi
 
       - name: "Retrieve failed step details"
         shell: bash
         id: validate-fail-retrieval
         if: ${{ failure() && steps.validate-deployment.conclusion == 'failure '}}
-        run: echo "${{ steps.validate-deployment.outputs }}"
+        run:  echo "failure step completed"  #echo "${{ steps.validate-deployment.outputs }}"
